package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"io"
	"io/fs"
	"os"
	"sort"
	"strings"
)

func main() {
	if err := run(os.Args[1:], os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string, out io.Writer) error {
	if len(args) > 1 {
		return errors.New("usage: apisnapshot [package-dir]")
	}

	dir := "./pkg/observex"
	if len(args) == 1 {
		dir = args[0]
	}

	snapshot, err := snapshotPackage(dir)
	if err != nil {
		return err
	}
	_, err = io.WriteString(out, snapshot)
	return err
}

func snapshotPackage(dir string) (string, error) {
	fset := token.NewFileSet()
	packages, err := parser.ParseDir(fset, dir, func(info fs.FileInfo) bool {
		name := info.Name()
		return !strings.HasSuffix(name, "_test.go") && strings.HasSuffix(name, ".go")
	}, 0)
	if err != nil {
		return "", fmt.Errorf("parse %s: %w", dir, err)
	}

	pkg, ok := packages["observex"]
	if !ok {
		if len(packages) != 1 {
			return "", fmt.Errorf("expected one package named observex in %s", dir)
		}
		for _, candidate := range packages {
			pkg = candidate
		}
	}

	files := make([]string, 0, len(pkg.Files))
	for path := range pkg.Files {
		files = append(files, path)
	}
	sort.Strings(files)

	entries := make([]string, 0)
	for _, path := range files {
		file := pkg.Files[path]
		entries = append(entries, snapshotFile(fset, file)...)
	}
	sort.Strings(entries)

	var b strings.Builder
	b.WriteString("# Code generated by internal/tools/apisnapshot; DO NOT EDIT.\n")
	b.WriteString("package observex\n\n")
	for i, entry := range entries {
		if i > 0 {
			b.WriteByte('\n')
		}
		b.WriteString(entry)
		b.WriteByte('\n')
	}
	return b.String(), nil
}

func snapshotFile(fset *token.FileSet, file *ast.File) []string {
	entries := make([]string, 0)
	for _, decl := range file.Decls {
		switch decl := decl.(type) {
		case *ast.GenDecl:
			entries = append(entries, snapshotGenDecl(fset, decl)...)
		case *ast.FuncDecl:
			if entry, ok := snapshotFuncDecl(fset, decl); ok {
				entries = append(entries, entry)
			}
		}
	}
	return entries
}

func snapshotGenDecl(fset *token.FileSet, decl *ast.GenDecl) []string {
	entries := make([]string, 0)
	for _, spec := range decl.Specs {
		switch spec := spec.(type) {
		case *ast.TypeSpec:
			if spec.Name.IsExported() {
				entries = append(entries, snapshotTypeSpec(fset, spec))
			}
		case *ast.ValueSpec:
			entries = append(entries, snapshotValueSpec(fset, decl.Tok.String(), spec)...)
		}
	}
	return entries
}

func snapshotTypeSpec(fset *token.FileSet, spec *ast.TypeSpec) string {
	prefix := "type " + spec.Name.Name
	if spec.Assign.IsValid() {
		return prefix + " = " + exprString(fset, spec.Type)
	}

	switch typ := spec.Type.(type) {
	case *ast.StructType:
		return prefix + " " + snapshotStruct(fset, typ)
	case *ast.InterfaceType:
		return prefix + " " + snapshotInterface(fset, typ)
	default:
		return prefix + " " + exprString(fset, spec.Type)
	}
}

func snapshotStruct(fset *token.FileSet, typ *ast.StructType) string {
	lines := make([]string, 0)
	for _, field := range typ.Fields.List {
		fieldType := exprString(fset, field.Type)
		tag := ""
		if field.Tag != nil {
			tag = " " + field.Tag.Value
		}

		if len(field.Names) == 0 {
			if exportedEmbeddedName(field.Type) != "" {
				lines = append(lines, "    "+fieldType+tag)
			}
			continue
		}
		for _, name := range field.Names {
			if name.IsExported() {
				lines = append(lines, "    "+name.Name+" "+fieldType+tag)
			}
		}
	}
	if len(lines) == 0 {
		return "struct {}"
	}
	return "struct {\n" + strings.Join(lines, "\n") + "\n}"
}

func snapshotInterface(fset *token.FileSet, typ *ast.InterfaceType) string {
	lines := make([]string, 0)
	for _, field := range typ.Methods.List {
		if len(field.Names) == 0 {
			if exportedEmbeddedName(field.Type) != "" {
				lines = append(lines, "    "+exprString(fset, field.Type))
			}
			continue
		}
		for _, name := range field.Names {
			if name.IsExported() {
				lines = append(lines, "    "+name.Name+funcTypeString(fset, field.Type))
			}
		}
	}
	if len(lines) == 0 {
		return "interface {}"
	}
	return "interface {\n" + strings.Join(lines, "\n") + "\n}"
}

func snapshotValueSpec(fset *token.FileSet, kind string, spec *ast.ValueSpec) []string {
	entries := make([]string, 0, len(spec.Names))
	for i, name := range spec.Names {
		if !name.IsExported() {
			continue
		}
		parts := []string{kind, name.Name}
		if spec.Type != nil {
			parts = append(parts, exprString(fset, spec.Type))
		}
		if i < len(spec.Values) {
			parts = append(parts, "=", exprString(fset, spec.Values[i]))
		}
		entries = append(entries, strings.Join(parts, " "))
	}
	return entries
}

func snapshotFuncDecl(fset *token.FileSet, decl *ast.FuncDecl) (string, bool) {
	if !decl.Name.IsExported() {
		return "", false
	}
	if decl.Recv == nil {
		return "func " + decl.Name.Name + funcTypeString(fset, decl.Type), true
	}
	if exportedReceiverName(decl.Recv) == "" {
		return "", false
	}
	return "func (" + receiverString(fset, decl.Recv) + ") " + decl.Name.Name + funcTypeString(fset, decl.Type), true
}

func funcTypeString(fset *token.FileSet, node ast.Node) string {
	raw := exprString(fset, node)
	if strings.HasPrefix(raw, "func") {
		return strings.TrimPrefix(raw, "func")
	}
	return " " + raw
}

func receiverString(fset *token.FileSet, recv *ast.FieldList) string {
	if recv == nil || len(recv.List) == 0 {
		return ""
	}
	field := recv.List[0]
	typ := exprString(fset, field.Type)
	if len(field.Names) == 0 {
		return typ
	}
	return field.Names[0].Name + " " + typ
}

func exportedReceiverName(recv *ast.FieldList) string {
	if recv == nil || len(recv.List) == 0 {
		return ""
	}
	return exportedEmbeddedName(recv.List[0].Type)
}

func exportedEmbeddedName(expr ast.Expr) string {
	switch expr := expr.(type) {
	case *ast.Ident:
		if expr.IsExported() {
			return expr.Name
		}
	case *ast.StarExpr:
		return exportedEmbeddedName(expr.X)
	case *ast.SelectorExpr:
		if expr.Sel.IsExported() {
			return expr.Sel.Name
		}
	case *ast.IndexExpr:
		return exportedEmbeddedName(expr.X)
	case *ast.IndexListExpr:
		return exportedEmbeddedName(expr.X)
	}
	return ""
}

func exprString(fset *token.FileSet, node ast.Node) string {
	var b bytes.Buffer
	if err := printer.Fprint(&b, fset, node); err != nil {
		return "<invalid>"
	}
	return strings.Join(strings.Fields(b.String()), " ")
}
