name: Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: observex-integration-${{ github.ref }}
  cancel-in-progress: true

env:
  GOWORK: "off"

jobs:
  integration:
    runs-on: [self-hosted, Linux, X64, ci-observex]
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Integration
        run: GOWORK=off make integration
